host: server.ashinnotfound.top
spring:
    config:
        import: nacos:wassup-auth.yml
    cloud:
        nacos:
            config:
                server-addr: ${host}
                namespace: bf31153c-9b8a-449b-a45d-5d20d0c6f460